name: Makefile CI

on:
  push:
    branches: ["dev"]
    tags:
    - '*'
  pull_request:
    tags:
    - '*'
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from file
        id: get_version
        run: |
          VERSION=$(cut -d "'" -f2 < pwnagotchi/_version.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo '${{ env.VERSION }}'

      - name: Print version from bash
        run: echo $VERSION

      - name: Install qemu dependencies
        run: sudo apt update && sudo apt install qemu-user-static qemu-utils xz-utils -y

      - name: Build img file
        run: ls -la .; pwd; make all

      - name: Transfer .img to docker and give permissions
        run: sudo chown runner:docker "pwnagotchi-rpi-bullseye-armhf.img"

      - name: Compress .img file to an .img.xz
        run: ls -la .; pwd; xz -z "pwnagotchi-rpi-bullseye-armhf.img"

      - name: Change name of .img.xz to add version
        run: mv "pwnagotchi-rpi-bullseye-armhf.img.xz" "pwnagotchi-rpi-bullseye-$VERSION-armhf.img.xz"

      - name: Release
        uses: softprops/action-gh-release@v1
        token: ${{ secrets.TOKEN }}
        name: Release ${{ env.VERSION }}
        tag: ${{ env.VERSION }}
        with:
          files: pwnagotchi-rpi-bullseye-${{ env.VERSION }}-armhf.img.xz
