name: Makefile CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from file
        id: get_version
        run: |
          VERSION=$(cut -d "'" -f2 < pwnagotchi/_version.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo "Version: ${{ env.VERSION }}"

      - name: Install qemu dependencies
        run: sudo apt update && sudo apt install qemu-user-static qemu-utils xz-utils -y

      - name: Build img file
        run: ls -la .; pwd; make all

      - name: Transfer .img to docker and give permissions
        run: sudo chown runner:docker "pwnagotchi-rpi-bullseye-armhf.img"

      - name: Compress .img file to an .img.xz
        run: ls -la .; pwd; xz -z "pwnagotchi-rpi-bullseye-armhf.img"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "pwnagotchi-rpi-bullseye-armhf.img.xz"
          token: ${{ secrets.TOKEN }}
          draft: false
          prerelease: false
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pwnagotchi-rpi-bullseye-armhf.img.xz
          asset_name: pwnagotchi-rpi-bullseye-${{ env.VERSION }}-armhf.img.xz
          asset_content_type: application/octet-stream
